version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./cache_service.db

  tests:
    build:
      context: .
    command: ["pytest", "tests/"]  # This runs the tests when you explicitly run the service
    volumes:
      - .:/app
    entrypoint: ["/bin/bash", "-c", "pytest tests/"]  # Runs pytest directly when triggered
